from setuptools import setup, find_packages
import pathlib

here = pathlib.Path(__file__).parent.resolve()

setup(
    name="openlongcontext",
    version="1.0.0",
    description="Production-ready FastAPI service and research platform for long-context document QA and retrieval with OpenAI agents integration.",
    long_description=(here / "README.md").read_text(),
    long_description_content_type="text/markdown",
    author="Nik Jois",
    author_email="nikjois@llamasearch.ai",
    url="https://github.com/openlongcontext/openlongcontext",
    license="Apache-2.0",
    packages=find_packages(),
    include_package_data=True,
    python_requires=">=3.9",
    install_requires=[
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "openai>=1.0.0",
        "torch>=2.1.0",
        "torchvision>=0.16.0",
        "transformers>=4.35.0",
        "datasets>=2.14.0",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "pandas>=2.1.0",
        "scikit-learn>=1.3.0",
        "omegaconf>=2.3.0",
        "hydra-core>=1.3.0",
        "pyyaml>=6.0.0",
        "tqdm>=4.65.0",
        "rich>=13.6.0",
        "pydantic>=2.0.0",
        "python-multipart>=0.0.6",
        "aiofiles>=23.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "pytest-asyncio>=0.21.0",
            "pytest-xdist>=3.4.0",
            "mypy>=1.6.0",
            "ruff>=0.1.0",
            "build>=1.0.0",
            "black>=23.10.0",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "pre-commit>=3.0.0",
        ],
        "research": [
            "wandb>=0.16.0",
            "mlflow>=2.8.0",
            "tensorboard>=2.15.0",
            "matplotlib>=3.8.0",
            "seaborn>=0.13.0",
            "scikit-learn>=1.3.0",
            "jupyter>=1.0.0",
            "optuna>=3.4.0",
            "pymc>=5.9.0",
        ],
        "agents": [
            "openai>=1.0.0",
            "asyncio-throttle>=1.0.0",
            "tiktoken>=0.5.0",
        ],
        "all": [
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "pytest-asyncio>=0.21.0",
            "pytest-xdist>=3.4.0",
            "mypy>=1.6.0",
            "ruff>=0.1.0",
            "build>=1.0.0",
            "black>=23.10.0",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "pre-commit>=3.0.0",
            "wandb>=0.16.0",
            "mlflow>=2.8.0",
            "tensorboard>=2.15.0",
            "matplotlib>=3.8.0",
            "seaborn>=0.13.0",
            "scikit-learn>=1.3.0",
            "jupyter>=1.0.0",
            "optuna>=3.4.0",
            "pymc>=5.9.0",
            "openai>=1.0.0",
            "asyncio-throttle>=1.0.0",
            "tiktoken>=0.5.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "openlongcontext=openlongcontext.cli:main",
            "openlongcontext-experiment=openlongcontext.cli.run_experiment:main",
            "openlongcontext-sweep=openlongcontext.cli.sweep:main",
            "openlongcontext-analyze=openlongcontext.cli.analyze_results:main",
            "openlongcontext-ablate=openlongcontext.cli.ablate:main",
        ],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
        "Framework :: FastAPI",
    ],
    keywords=[
        "long-context", "scaling-laws", "transformer", "efficient-attention", 
        "memory", "deep-learning", "openai", "agents", "fastapi", "nlp",
        "question-answering", "document-processing", "ai", "ml", "research"
    ],
    project_urls={
        "Homepage": "https://github.com/openlongcontext/openlongcontext",
        "Documentation": "https://openlongcontext.github.io/openlongcontext/",
        "Repository": "https://github.com/openlongcontext/openlongcontext",
        "Bug Tracker": "https://github.com/openlongcontext/openlongcontext/issues",
        "Changelog": "https://github.com/openlongcontext/openlongcontext/releases",
    },
)